# gitversion will change the version number
version: x-{build}

branches:
  only:
    - master

configuration: Release
os: Visual Studio 2015

init:
  - git config --global core.autocrlf input
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:git_token):x-oauth-basic@github.com`n"
  - git config --global user.email "noreply@emanon.org"
  - git config --global user.name "Appveyor CI"

cache:
  - packages -> **\packages.config      # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

environment:
  COVERALLS_REPO_TOKEN:
    secure: j4sELCwhVRRjNXFVhjPZjdG4y2itz8jrExhlyDU/lTiLlRQ/P4brB69MGQRFBQae
  snk_secret:
    secure: 5QzEIgiDqTIrZruPaIQIvTlNMl5BZ7TGEps7ALyBfHE=
  git_token:
    secure: NeX5NCOUXsCLc1UjTJjqB9F02FZ8Wq0VsxqTXC8kBdyK6zjxjebrf/9Da2sY1Kql

# tools we need for bulding/testing/deploying
install:
  - choco install gitversion.portable -pre -y
  # - npm install gh-pages -g
  #- choco install docfx
  # No longer signing the assembly
  #- nuget install secure-file -ExcludeVersion
  #- if defined snk_secret secure-file\tools\secure-file -decrypt src\ipfs.ci.snk.enc -secret %snk_secret% -out src\ipfs.dev.snk

pull_requests:
  do_not_increment_build_number: true

# gitversion will change the assembly info
assembly_info:
  patch: false

before_build:
  - nuget restore

# Determine the version
  - ps: gitversion /output buildserver /updateAssemblyInfo >gitversion.log

build:
  project: Bridge.sln
  publish_nuget: false
  verbosity: minimal

after_build:
# Build documentation in doc\_site
  #- tools\docfx\docfx doc\docfx.json
  #- if defined git_token gh-pages -d doc\_site -m "new docs %GitVersion_FullSemVer%"

# Build nuget package
  - cmd: nuget pack Core\Bridge.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "Makaretu.Bridge.%GitVersion_NuGetVersion%.nupkg"

after_test: 
# Generate coverage report
   # - packages\OpenCover.4.6.210-rc\tools\OpenCover.Console.exe -register:user -filter:"+[Ipfs*]* -[*Tests]* -[Ipfs.Core]SHA3*" -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:test//bin/Release/Ipfs.Core.Tests.dll" -output:coverage.xml
   # - if defined COVERALLS_REPO_TOKEN packages\coveralls.net.0.6.0\tools\csmacnz.coveralls.exe --opencover -i ./coverage.xml --serviceName appveyor --jobId %APPVEYOR_BUILD_NUMBER%

# publish NuGet package on tag build
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
deploy:
- provider: NuGet
  api_key:
    secure: OdmGEj/l0K0ZPDmXAYx+fryCzV012eTrM29ALBuL0waxvwLvrufdDXiI+1iNhWEG
  on:
    appveyor_repo_tag: true
